server:
  port: 80
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/bookdb?characterEncoding=utf8
      username: root
      password: Zjh906042
      driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false